### ISSUE TITLE
FEEDBACK ON YOUR SYSTEM_DOCU

### ISSUE THREAD

**Issue by thirdygayares** [LibraryWebAppSVFC/LibraryWebApplication_Documentation#1]
1. Please change the title remove umak
2. Yung work breakdown structure di nagutugma sa Project Features
3. Di nagtutugma yung use case sa features niyo
4. Yung ERD niyo mali

**Comment by TheLastWeaboo** [comment]
> 1. Please change the title remove umak
> 2. Yung work breakdown structure di nagutugma sa Project Features
> 3. Di nagtutugma yung use case sa features niyo
> 4. Yung ERD niyo mali

-Changed the title name
-Updated the work breakdown structure 
-Updated the use case to be in line with the features
-Haven't fixed yet, can we get a template or an example for the ERD sir? Because we have based on the template you have given before

**Comment by TheLastWeaboo** [comment]
> 1. Please change the title remove umak
> 2. Yung work breakdown structure di nagutugma sa Project Features
> 3. Di nagtutugma yung use case sa features niyo
> 4. Yung ERD niyo mali

-Changed the title name
-Updated the work breakdown structure 
-Updated the use case to be in line with the features
-Haven't fixed yet, can we get a template or an example for the ERD sir? Because we have based on the template you have given before

@thirdygayares

**Comment by TheLastWeaboo** [comment]
Erd Done
