### ISSUE TITLE
It looks like there was feedback provided to your group three weeks ago that hasn't been addressed.

### ISSUE THREAD

**Issue by thirdygayares** [LibraryWebAppSVFC/LibraryWebApplication_Documentation#2]
![image](https://github.com/user-attachments/assets/33d1b049-66b8-4ab8-a276-75e6dc55de1f)
![image](https://github.com/user-attachments/assets/cebe3d1e-bc93-4bae-bdcd-f92ebb546ef1)
![image](https://github.com/user-attachments/assets/1a0f8ea4-fd88-481f-a90f-ec702274989c)

**Comment by TheLastWeaboo** [comment]
Erd changed
